### PR TITLE
Add support for CoffeeScript.

### LINKED ISSUE #51: Add CoffeeScript support

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #51

### CODE REVIEW

**Comment by henrypijames** [comment]
What's the downside of activating the (not yet perfect) CoffeeScript support now? Is there any risk that this would affect things unrelated to CoffeeScript? If you're unsure whether the current rules covers everything that needs to be covered, wouldn't it help to activate the CoffeeScript support and get some user feedback?

**Comment by XhmikosR** [comment]
It won't affect other things. As for feedback, I guess I could do that, though I don't think I will get any.

**Comment by henrypijames** [comment]
Sure you'll get some feedback, not the least from me. :)

**Comment by XhmikosR** [comment]
@henrypijames: I'm gonna merge this now. I'll wait for feedback.

**Pull request merged**
