### PR TITLE
add DeelX RegExpr search engine (using Scintilla's SCI_OWNREGEX API)

### PR DESCRIPTION
**Pull request by RaiKoHoff**
will handle request XhmikosR/notepad2-mod#148

### CODE REVIEW

**Comment by XhmikosR** [comment]
I have no idea what this is even about. I don't feel safe merging this at this point.

**Comment by RaPeHoff** [comment]
To give you an idea:
Notepad2 and also the maintaining fork notepad2-mod are using Scintilla's internal regexpr engine,
which has its limitations (see https://github.com/XhmikosR/notepad2-mod/issues/148).
In wise forsight, the developer of Scintilla creates an interface (activated by preprocessor define SCI_OWNREGEX), to embed your own RegExpr search (and replace) engine. This is what this pull-request is about.

**Comment by RaPeHoff** [comment]
fixing the coop-work with "Whole Word" and "Start of Word" check options together with RegExpr search

**Comment by RaPeHoff** [comment]
... maintenance (no feature) fork here.

**Pull request closed without merging**
