### PR TITLE
fix warning C4819 and copyright sign been displayed as question mark on non-Latin system

### PR DESCRIPTION
**Pull request by zufuliu**
fix warning C4819: "The file contains a character that cannot be represented in the current code page. Save the file in Unicode format to prevent data loss." when build on non-Latin system. 
On the other hand when double click Edit.c in Visual Studio, an error dialog appears, says "Some bytes have been replaced with the Unicode substitution character while loading file with XXXX encoding. Saving the will not preserve the original contents".

By the way the copyright sign is displayed as question mark on non-Latin system.

After these changes, the Unicode version of Inno Setup sholud be used: http://www.jrsoftware.org/ishelp/index.php?topic=unicode

### CODE REVIEW

**Comment by zufuliu** [comment]
These non-ASCII char is found by run
```
grep --exclude-dir=.git --exclude-dir=.vs --exclude-dir=bin --exclude=*.ico --exclude=*.cur --exclude=*.bmp --exclude=*.png --exclude=*.html --exclude=*.jpg  --exclude=*.vcxproj* -P -nr "[^\x00-\x7f]" .
```

open file found by grep, reload file as UTF-8 (previous PR), goto corresponding line, you will see scintilla displays them in xHH format.

**Comment by XhmikosR** [comment]
Sorry, this isn't needed. Especially for Inno Setup. As for the rest of the files, you can always save them as UTF16 with BOM instead of that.

**Comment by zufuliu** [comment]
@XhmikosR ok. I suggest you to save them as UTF16 with BOM, sine I cannot open them correctly.  I don't known what encoding these file is, maybe some Europe encoding.

**Comment by XhmikosR** [comment]
They are normal ASCII files. Inno Setup does the conversion automatically. VS no idea, I don't have such environments.

**Comment by zufuliu** [comment]
@XhmikosR no, thay are not 7 bit ASCII. If they are, these file should be loaded as UTF-8 if default encoding is set to UTF-8. as example the copyright sign U+00A9 in UTF-8 is \xc2\xa9.
What Notepad2 displayed as ASCII is actually user's system default code page (encdong), not 7 bit ASCII.

**Comment by XhmikosR** [comment]
Either way, they display fine on my machine. And Visual Studio doesn't show any warnings nor it changes anything when saving those files.

**Comment by zufuliu** [comment]
you can load License.txt into a hex editor to ensure they this:
```
4E 6F 74 65 70 61 64 32 20 43 6F 70 79 72 69 67                   Notepad2 Copyrig
68 74 20 A9 20 32 30 30 34 2D 32 30 31 31 20 46                   ht © 2004-2011 F
```
look the copyright sign at offset 0x13, which is A9. which may not be interpreted correctly in other locale / encoding / code page.  

look at these wiki pages:
https://en.wikipedia.org/wiki/GB_2312
https://en.wikipedia.org/wiki/Big5
https://en.wikipedia.org/wiki/Shift_JIS

0xA9 is used as an leader byte or code for non-Latin character.

**Comment by XhmikosR** [comment]
I'm not saying you are wrong. But you are mixing different things.

The distrib/license.txt won't change because I don't want to use Inno Setup Unicode; everything is English only and I plan it to stay that way.
The rc file can't be saved as UTF8.

And generally this whole thing creates more issues to me and my environment than it might fix for you.

So I'm going to pass on this.

**Comment by zufuliu** [comment]
OK, I should mention that, this PR did change license, readme and Inno Setup script to UTF-8 (because of copyright sign), but change Edit.c, Notepad2.c, Version.h and Notepad2.rc to 7-bit ASCII, the later is what I really care about.

can I make a new PR just for the later? or you will do it you self?

**Comment by XhmikosR** [comment]
Can you force push this branch and remove the distrib and license changes? Then I can have a look for the rest although I don't like this approach because I have to look up which character is what. That is why I suggested changing the file encoding to something Visual Studio understands for those files.

**Comment by zufuliu** [comment]
you can set Notepad2-mod's default encoding to UTF-8, and the open Edit.c (this time loaded as ANSI), then reload as UTF-8 (previous PR).
for Edit.c goto line 1771 for StrChr,  line 4113 for ISDELIMITER
for Notepad2.c goto line 3674, 3675, 3676, 3690, 3691
for Notepad2.rc goto line 1612 for IDS_CMDLINEHELP
for Version.h line 40 and 41 contains copyright sign.

**Comment by zufuliu** [comment]
@XhmikosR It's done.

**Comment by XhmikosR** [comment]
Should be fixed in the latest master.

**Comment by zufuliu** [comment]
@XhmikosR Visual C++ compiler doesn't understand UTF-8 without BOM, through the Text Editor does if Options -> Text Editor -> "Audo-detect UTF-8 encoding without signature" is checked.

**Comment by XhmikosR** [comment]
You mean for Version.h?

The reason I skipped the BOM marker is because then git treats the files as binary.

**Comment by zufuliu** [comment]
Version.h does not cause build fail, only cause copyright sign displayed as question mark.
Edit.c however doses, because of string literal used. 
Notepad2.c is fine, alll non ascii char is in comment.

**Comment by XhmikosR** [comment]
Yeah, but then git will treat the file as binary which I don't want...

**Comment by zufuliu** [comment]
that's why I suggest save them as 7-bit ASCII using character escape sequence,

for Notepa2.c, those non-ASCII comments can be completely removed, they does not provide useful info and can only be understood by people  who known that language (maybe French?).

**Comment by XhmikosR** [comment]
Notepad2.c doesnt' have any comments. https://github.com/XhmikosR/notepad2-mod/commit/532e80f67ed8257ef5cce7aa3113b9f40962958b

So, it's basically Edit.c. And `ISDELIMITER` seems to be actually unused.

**Comment by zufuliu** [comment]
ISDELIMITER originally has been used for split long line. it will be used in the future I think, because  EditWrapToColumn() does not works as expected.

**Pull request closed without merging**
