### PR TITLE
fix issue #37 Block select (Alt-mouse-drag) causes AV 

### PR DESCRIPTION
**Pull request by zufuliu**
fix issue #37 Block select (Alt-mouse-drag) causes AV

### CODE REVIEW

**Comment by XhmikosR** [comment]
@zufuliu: thanks for the patch.

**Comment by zufuliu** [comment]
The code now updated, previous one cause new problem.

**Comment by szepeviktor** [comment]
@XhmikosR Is there a way to land this PR?
It is an ancient bug.

**Comment by szepeviktor** [comment]
@XhmikosR Please merge this one.
Thanks.

**Pull request merged**
